/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as web3 from '@solana/web3.js'
import * as beet from '@metaplex-foundation/beet'
import * as beetSolana from '@metaplex-foundation/beet-solana'
import { PaymentFeePayer, paymentFeePayerBeet } from './PaymentFeePayer'
export type FeesConfig = {
  fee: number
  feePayer: PaymentFeePayer
  discountMint: beet.COption<web3.PublicKey>
  feeReduction: beet.COption<number>
}

/**
 * @category userTypes
 * @category generated
 */
export const feesConfigBeet = new beet.FixableBeetArgsStruct<FeesConfig>(
  [
    ['fee', beet.u16],
    ['feePayer', paymentFeePayerBeet],
    ['discountMint', beet.coption(beetSolana.publicKey)],
    ['feeReduction', beet.coption(beet.u16)],
  ],
  'FeesConfig'
)
