/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'
import { type FeesConfig, feesConfigBeet } from '../types/FeesConfig'
import { type RewardsConfig, rewardsConfigBeet } from '../types/RewardsConfig'

/**
 * @category Instructions
 * @category EditMarketplace
 * @category generated
 */
export type EditMarketplaceInstructionArgs = {
  feesConfig: beet.COption<FeesConfig>
  rewardsConfig: beet.COption<RewardsConfig>
}
/**
 * @category Instructions
 * @category EditMarketplace
 * @category generated
 */
export const editMarketplaceStruct = new beet.FixableBeetArgsStruct<
  EditMarketplaceInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['feesConfig', beet.coption(feesConfigBeet)],
    ['rewardsConfig', beet.coption(rewardsConfigBeet)],
  ],
  'EditMarketplaceInstructionArgs'
)
/**
 * Accounts required by the _editMarketplace_ instruction
 *
 * @property [_writable_, **signer**] signer
 * @property [_writable_] marketplace
 * @property [_writable_] accessMint (optional)
 * @category Instructions
 * @category EditMarketplace
 * @category generated
 */
export type EditMarketplaceInstructionAccounts = {
  signer: web3.PublicKey
  marketplace: web3.PublicKey
  accessMint?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const editMarketplaceInstructionDiscriminator = [
  63, 97, 25, 236, 101, 55, 240, 177,
]

/**
 * Creates a _EditMarketplace_ instruction.
 *
 * Optional accounts that are not provided default to the program ID since
 * this was indicated in the IDL from which this instruction was generated.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category EditMarketplace
 * @category generated
 */
export function createEditMarketplaceInstruction(
  accounts: EditMarketplaceInstructionAccounts,
  args: EditMarketplaceInstructionArgs,
  programId = new web3.PublicKey('7KES27SK4AdZCCVj7nWgf5rUBFgyDMNSHEwgu7tvbnZW')
) {
  const [data] = editMarketplaceStruct.serialize({
    instructionDiscriminator: editMarketplaceInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.marketplace,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.accessMint ?? programId,
      isWritable: accounts.accessMint != null,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
