/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from '@solana/spl-token'
import * as beet from '@metaplex-foundation/beet'
import * as web3 from '@solana/web3.js'

/**
 * @category Instructions
 * @category RegisterBuy
 * @category generated
 */
export type RegisterBuyInstructionArgs = {
  amount: number
}
/**
 * @category Instructions
 * @category RegisterBuy
 * @category generated
 */
export const registerBuyStruct = new beet.BeetArgsStruct<
  RegisterBuyInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ['instructionDiscriminator', beet.uniformFixedSizeArray(beet.u8, 8)],
    ['amount', beet.u32],
  ],
  'RegisterBuyInstructionArgs'
)
/**
 * Accounts required by the _registerBuy_ instruction
 *
 * @property [_writable_, **signer**] signer
 * @property [_writable_] marketplace
 * @property [] product
 * @property [] paymentMint
 * @property [_writable_] buyerVault
 * @property [_writable_] sellerVault
 * @property [_writable_] marketplaceVault (optional)
 * @property [_writable_] bountyVault (optional)
 * @category Instructions
 * @category RegisterBuy
 * @category generated
 */
export type RegisterBuyInstructionAccounts = {
  signer: web3.PublicKey
  marketplace: web3.PublicKey
  product: web3.PublicKey
  paymentMint: web3.PublicKey
  buyerVault: web3.PublicKey
  sellerVault: web3.PublicKey
  marketplaceVault?: web3.PublicKey
  bountyVault?: web3.PublicKey
  rent?: web3.PublicKey
  systemProgram?: web3.PublicKey
  tokenProgram?: web3.PublicKey
  anchorRemainingAccounts?: web3.AccountMeta[]
}

export const registerBuyInstructionDiscriminator = [
  49, 64, 206, 28, 74, 111, 166, 179,
]

/**
 * Creates a _RegisterBuy_ instruction.
 *
 * Optional accounts that are not provided default to the program ID since
 * this was indicated in the IDL from which this instruction was generated.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category RegisterBuy
 * @category generated
 */
export function createRegisterBuyInstruction(
  accounts: RegisterBuyInstructionAccounts,
  args: RegisterBuyInstructionArgs,
  programId = new web3.PublicKey('7KES27SK4AdZCCVj7nWgf5rUBFgyDMNSHEwgu7tvbnZW')
) {
  const [data] = registerBuyStruct.serialize({
    instructionDiscriminator: registerBuyInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.signer,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.marketplace,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.product,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.paymentMint,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.buyerVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.sellerVault,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.marketplaceVault ?? programId,
      isWritable: accounts.marketplaceVault != null,
      isSigner: false,
    },
    {
      pubkey: accounts.bountyVault ?? programId,
      isWritable: accounts.bountyVault != null,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
  ]

  if (accounts.anchorRemainingAccounts != null) {
    for (const acc of accounts.anchorRemainingAccounts) {
      keys.push(acc)
    }
  }

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
